### ISSUE TITLE
question about environment

### ISSUE THREAD

**Issue by toinBe** [FIVEYOUNGWOO/Simple-Reinforcement-Learning-Example#1]
I am conducting research on mobile robot control based on reinforcement learning at Peking University.

Do you think it is possible to modify the code you provide and reconfigure it into an environment for controlling the robot?

**Comment by FIVEYOUNGWOO** [comment]
> I am conducting research on mobile robot control based on reinforcement learning at Peking University.
> 
> Do you think it is possible to modify the code you provide and reconfigure it into an environment for controlling the robot?

Hi, thank you for your good question.

The basic shower example provides an insight into the reinforcement learning algorithm. I think that you need larger environments such as control of mobile robots or a physically sensor-based environment. 

I recommend an Open AI Gym-based customizing RL environment for your project. 

Best of luck :)
